// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCAProject.Data;

namespace WCAProject.Migrations
{
    [DbContext(typeof(WCAProjectContext))]
    partial class WCAProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WCAProject.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CredibleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZcountyId")
                        .HasColumnType("int");

                    b.Property<int?>("ZinsuranceId")
                        .HasColumnType("int");

                    b.Property<int?>("ZraceId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("cfirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_other_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("insurance2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nextactionnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ssn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.HasIndex("ZcountyId");

                    b.HasIndex("ZinsuranceId");

                    b.HasIndex("ZraceId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WCAProject.Models.ClientService", b =>
                {
                    b.Property<int>("ClientServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ZcaresreasonId")
                        .HasColumnType("int");

                    b.Property<int?>("ZhearaboutId")
                        .HasColumnType("int");

                    b.Property<int?>("ZinternalId")
                        .HasColumnType("int");

                    b.Property<int?>("ZinternalcategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ZlocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ZopotherId")
                        .HasColumnType("int");

                    b.Property<int?>("ZplatformId")
                        .HasColumnType("int");

                    b.Property<int?>("ZprogramsId")
                        .HasColumnType("int");

                    b.Property<int?>("ZreasonId")
                        .HasColumnType("int");

                    b.Property<int?>("ZresourcereasonId")
                        .HasColumnType("int");

                    b.Property<int?>("ZschoolId")
                        .HasColumnType("int");

                    b.Property<int?>("ZsiteId")
                        .HasColumnType("int");

                    b.Property<int?>("ZstatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ZworkerId")
                        .HasColumnType("int");

                    b.Property<string>("bhrs_diag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("child")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("closedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("court")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("drug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("drug_da")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eval_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("family_avail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("harm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("harm_da")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("intext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("intnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("legal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maiden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mental")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("much_often")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("optype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("overdose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pocdates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pregnant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("psychologist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("recdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("schoolloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("site2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("site_other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("substance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trackdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tracknote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("veteran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("what_sub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("withdraw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("withdraw_da")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientServiceId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ZcaresreasonId");

                    b.HasIndex("ZhearaboutId");

                    b.HasIndex("ZinternalId");

                    b.HasIndex("ZinternalcategoryId");

                    b.HasIndex("ZlocationId");

                    b.HasIndex("ZopotherId");

                    b.HasIndex("ZplatformId");

                    b.HasIndex("ZprogramsId");

                    b.HasIndex("ZreasonId");

                    b.HasIndex("ZresourcereasonId");

                    b.HasIndex("ZschoolId");

                    b.HasIndex("ZsiteId");

                    b.HasIndex("ZstatusId");

                    b.HasIndex("ZworkerId");

                    b.ToTable("ClientServices");
                });

            modelBuilder.Entity("WCAProject.Models.Clineitem", b =>
                {
                    b.Property<int>("ClineitemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ZworkerId")
                        .HasColumnType("int");

                    b.Property<int?>("ZactionId")
                        .HasColumnType("int");

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ldate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClineitemId");

                    b.HasIndex("ClientServiceId");

                    b.HasIndex("ZworkerId");

                    b.HasIndex("ZactionId");

                    b.ToTable("Clineitems");
                });

            modelBuilder.Entity("WCAProject.Models.ScaScreen", b =>
                {
                    b.Property<int>("ScaScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientServiceId")
                        .HasColumnType("int");

                    b.Property<string>("asddiagnosis")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("currentcounty")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("gennote")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("halfwayshelter")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("managedcaretype")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("meetcriteria")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("outsidevbh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("privateinsurance")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("privateinsurer")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("recentlymove")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("referraldetails")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("referralsource")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("requestedlocation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("servicerequested")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("shelterdetails")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("treatmenthistory")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("wasstatenotified")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("whyfamilyseen")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("wsclinic")
                        .HasColumnType("int");

                    b.HasKey("ScaScreenId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientServiceId");

                    b.ToTable("ScaScreen");
                });

            modelBuilder.Entity("WCAProject.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("credible")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("service_desc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WCAProject.Models.Zaction", b =>
                {
                    b.Property<int>("ZactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("action")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZactionId");

                    b.ToTable("Zaction");
                });

            modelBuilder.Entity("WCAProject.Models.Zcaresreason", b =>
                {
                    b.Property<int>("ZcaresreasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("caresreason")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZcaresreasonId");

                    b.ToTable("Zcaresreason");
                });

            modelBuilder.Entity("WCAProject.Models.Zcounty", b =>
                {
                    b.Property<int>("ZcountyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("county")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZcountyId");

                    b.ToTable("Zcounty");
                });

            modelBuilder.Entity("WCAProject.Models.Zhearabout", b =>
                {
                    b.Property<int>("ZhearaboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("hearabout")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZhearaboutId");

                    b.ToTable("Zhearabout");
                });

            modelBuilder.Entity("WCAProject.Models.Zinsurance", b =>
                {
                    b.Property<int>("ZinsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("insurance")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZinsuranceId");

                    b.ToTable("Zinsurance");
                });

            modelBuilder.Entity("WCAProject.Models.Zinternal", b =>
                {
                    b.Property<int>("ZinternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("credstatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("internal_type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZinternalId");

                    b.ToTable("Zinternal");
                });

            modelBuilder.Entity("WCAProject.Models.Zinternalcategory", b =>
                {
                    b.Property<int>("ZinternalcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("internalsubcat")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZinternalcategoryId");

                    b.ToTable("Zinternalcategory");
                });

            modelBuilder.Entity("WCAProject.Models.Zlocation", b =>
                {
                    b.Property<int>("ZlocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("credstatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZlocationId");

                    b.ToTable("Zlocation");
                });

            modelBuilder.Entity("WCAProject.Models.Zopother", b =>
                {
                    b.Property<int>("ZopotherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("opother")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZopotherId");

                    b.ToTable("Zopother");
                });

            modelBuilder.Entity("WCAProject.Models.Zplatform", b =>
                {
                    b.Property<int>("ZplatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("internalId")
                        .HasColumnType("int");

                    b.Property<string>("opplatform")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ZplatformId");

                    b.ToTable("Zplatform");
                });

            modelBuilder.Entity("WCAProject.Models.Zprograms", b =>
                {
                    b.Property<int>("ZprogramsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("program_desc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("programs_id")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZprogramsId");

                    b.ToTable("Zprograms");
                });

            modelBuilder.Entity("WCAProject.Models.Zrace", b =>
                {
                    b.Property<int>("ZraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("race")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZraceId");

                    b.ToTable("Zrace");
                });

            modelBuilder.Entity("WCAProject.Models.Zreason", b =>
                {
                    b.Property<int>("ZreasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("final_reason")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("status_match")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZreasonId");

                    b.ToTable("Zreason");
                });

            modelBuilder.Entity("WCAProject.Models.Zreferralsource", b =>
                {
                    b.Property<int>("ZreferralsourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("referralsource")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZreferralsourceId");

                    b.ToTable("Zreferralsource");
                });

            modelBuilder.Entity("WCAProject.Models.Zresourcereason", b =>
                {
                    b.Property<int>("ZresourcereasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("resourceresult")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ZresourcereasonId");

                    b.ToTable("Zresourcereason");
                });

            modelBuilder.Entity("WCAProject.Models.Zschool", b =>
                {
                    b.Property<int>("ZschoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceOffered")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("displayname")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("schooldistrict")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("site")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("therapist")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZschoolId");

                    b.ToTable("Zschool");
                });

            modelBuilder.Entity("WCAProject.Models.Zsite", b =>
                {
                    b.Property<int>("ZsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("site")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZsiteId");

                    b.ToTable("Zsite");
                });

            modelBuilder.Entity("WCAProject.Models.Zstatus", b =>
                {
                    b.Property<int>("ZstatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("credstatus")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("inq_status")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("temp")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZstatusId");

                    b.ToTable("Zstatus");
                });

            modelBuilder.Entity("WCAProject.Models.Zworker", b =>
                {
                    b.Property<int>("ZworkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("report")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("worker")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ZworkerId");

                    b.ToTable("Zworker");
                });

            modelBuilder.Entity("WCAProject.Models.Zyesno", b =>
                {
                    b.Property<int>("ZyesnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yesno")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ZyesnoId");

                    b.ToTable("Zyesno");
                });

            modelBuilder.Entity("WCAProject.Models.Client", b =>
                {
                    b.HasOne("WCAProject.Models.Zcounty", "Zcounty")
                        .WithMany()
                        .HasForeignKey("ZcountyId");

                    b.HasOne("WCAProject.Models.Zinsurance", "Zinsurance")
                        .WithMany()
                        .HasForeignKey("ZinsuranceId");

                    b.HasOne("WCAProject.Models.Zrace", "Zrace")
                        .WithMany()
                        .HasForeignKey("ZraceId");
                });

            modelBuilder.Entity("WCAProject.Models.ClientService", b =>
                {
                    b.HasOne("WCAProject.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("WCAProject.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("WCAProject.Models.Zcaresreason", "Zcaresreason")
                        .WithMany()
                        .HasForeignKey("ZcaresreasonId");

                    b.HasOne("WCAProject.Models.Zhearabout", "Zhearabout")
                        .WithMany()
                        .HasForeignKey("ZhearaboutId");

                    b.HasOne("WCAProject.Models.Zinternal", "Zinternal")
                        .WithMany()
                        .HasForeignKey("ZinternalId");

                    b.HasOne("WCAProject.Models.Zinternalcategory", "Zinternalcategory")
                        .WithMany()
                        .HasForeignKey("ZinternalcategoryId");

                    b.HasOne("WCAProject.Models.Zlocation", "Zlocation")
                        .WithMany()
                        .HasForeignKey("ZlocationId");

                    b.HasOne("WCAProject.Models.Zopother", "Zopother")
                        .WithMany()
                        .HasForeignKey("ZopotherId");

                    b.HasOne("WCAProject.Models.Zplatform", "Zplatform")
                        .WithMany()
                        .HasForeignKey("ZplatformId");

                    b.HasOne("WCAProject.Models.Zprograms", "Zprograms")
                        .WithMany()
                        .HasForeignKey("ZprogramsId");

                    b.HasOne("WCAProject.Models.Zreason", "Zreason")
                        .WithMany()
                        .HasForeignKey("ZreasonId");

                    b.HasOne("WCAProject.Models.Zresourcereason", "Zresourcereason")
                        .WithMany()
                        .HasForeignKey("ZresourcereasonId");

                    b.HasOne("WCAProject.Models.Zschool", "Zschool")
                        .WithMany()
                        .HasForeignKey("ZschoolId");

                    b.HasOne("WCAProject.Models.Zsite", "Zsite")
                        .WithMany()
                        .HasForeignKey("ZsiteId");

                    b.HasOne("WCAProject.Models.Zstatus", "Zstatus")
                        .WithMany()
                        .HasForeignKey("ZstatusId");

                    b.HasOne("WCAProject.Models.Zworker", "Zworker")
                        .WithMany()
                        .HasForeignKey("ZworkerId");
                });

            modelBuilder.Entity("WCAProject.Models.Clineitem", b =>
                {
                    b.HasOne("WCAProject.Models.ClientService", "ClientService")
                        .WithMany()
                        .HasForeignKey("ClientServiceId");

                    b.HasOne("WCAProject.Models.Zworker", "Zworker")
                        .WithMany()
                        .HasForeignKey("ZworkerId");
                });

            modelBuilder.Entity("WCAProject.Models.ScaScreen", b =>
                {
                    b.HasOne("WCAProject.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("WCAProject.Models.ClientService", "ClientService")
                        .WithMany()
                        .HasForeignKey("ClientServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
